import type { Metadata } from "next";
import { Questrial } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const questrial = Questrial({
  variable: "--font-questrial",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${questrial.variable} dark font-questrial min-h-[100vh] bg-dark-1 text-white antialiased`}>
        <main className="container mx-auto px-3 md:px-0">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
